import { createId } from "../util.js";
import {
  GatewayConfigAdminError,
  type GatewayConfigResource
} from "./gatewayConfigTypes.js";

const RESOURCE_ID_PREFIXES = {
  providerConnection: "connection",
  canonicalModel: "canonical_model",
  modelDeployment: "deployment",
  wireBinding: "wire_binding",
  logicalModel: "logical_model",
  logicalModelTarget: "logical_target",
  accessProfile: "access_profile",
  modelGrant: "model_grant"
} as const satisfies Record<GatewayConfigResource, string>;

export function gatewayResourceId(resource: GatewayConfigResource, preparedId?: string) {
  const prefix = RESOURCE_ID_PREFIXES[resource];
  if (!preparedId) return createId(prefix);
  const uuidPattern = new RegExp(`^${prefix}_[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$`);
  if (!uuidPattern.test(preparedId)) {
    throw new GatewayConfigAdminError("gateway_config_prepared_id_invalid", 400, [{
      path: "id",
      message: "Prepared resource IDs must be generated by the gateway control plane."
    }]);
  }
  return preparedId;
}
